version: 0
allowPullRequests: public
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.closed
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
          - push
          - release
    payload:
      maxRunTime: 3600
      artifacts:
        public/build:
          path: /repo/artifacts
          type: directory
          expires: "{{ '14 days' | $fromNow }}"
      image: node:9.11.2
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - |
          set -e
          git clone {{event.head.repo.url}} repo
          cd repo
          git config advice.detachedHead false
          git checkout {{event.head.sha}}
          yarn
          yarn lint
          yarn test
          yarn build
          mkdir artifacts
          tar -czf artifacts/build.tar.gz build
    metadata:
      name: 'UI CI tests'
      description: 'Run linting, tests, etc'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla-releng/shipit-v2:dockerhub
    payload:
      artifacts:
        public/build:
          path: /home/worker/artifacts
          type: directory
          expires: "{{ '14 days' | $fromNow }}"
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - |
          set -e
          git clone {{event.head.repo.url}} repo
          cd repo
          git config advice.detachedHead false
          git checkout {{event.head.sha}}
          ./scripts/push-dockerimage.sh latest {{ event.head.repo.branch }}-{{event.head.sha}}
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    metadata:
      name: 'Generate docker image'
      description: 'Generate docker image'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla-releng/shipit-v2:dockerhub
    payload:
      artifacts:
        public/build:
          path: /home/worker/artifacts
          type: directory
          expires: "{{ '14 days' | $fromNow }}"
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - |
          set -e
          git clone -b {{ event.version }} {{ event.head.repo.url }} repo
          cd repo
          ./scripts/push-dockerimage.sh {{ event.version }}
    extra:
      github:
        env: true
        events:
          - release
    metadata:
      name: 'Generate docker image'
      description: 'Generate docker image'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
