version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.closed
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
          - push
          - release
    payload:
      maxRunTime: 3600
      artifacts:
        public/build:
          path: /repo/artifacts
          type: directory
          expires: "{{ '14 days' | $fromNow }}"
      image: node:9.11.2
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - |
          set -e
          git clone {{event.head.repo.url}} repo
          cd repo
          git config advice.detachedHead false
          git checkout {{event.head.sha}}
          yarn
          yarn lint
          yarn test
          yarn build
          mkdir artifacts
          tar -czf artifacts/build.tar.gz build
    metadata:
      name: 'UI CI tests'
      description: 'Run linting, tests, etc'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: public
